.
.TH CCC "1" "March 2024" "ccc" "User Commands"
.SH NAME
ccc \- Fast, small, hackable TUI file manager with no dependency
.SH SYNOPSIS
.B ccc
.SH DESCRIPTION
Soft fork of fff in C aiming for size and speed with no dependency, hackable with patches and configurable
.PP
.SH "Usage"
.
.nf

h: go to parent dir
j: scroll down
k: scroll up
l: go to child dir

left:  go to parent dir
down:  scroll down
up:    scroll up
right: go to child dir

enter: go to child dir/open file
backspace: go to parent dir

g: go to top
G: go to bottom

ctrl+u: jump up
ctrl+d: jump down

t: go to trash dir
~: go to home dir
-: go to previous dir
z: refresh current dir
:: go to a directory by typing
u: sort files

.: toggle hidden files
i: toggle file details
X: toggle executable
!: open shell in current dir

A: show directory disk usage/block size

f: new file
n: new dir
r: rename

space: mark file
a: mark all files in directory
d: trash

?: show help
q: exit with last dir written to file
ctrl+c exit without writing last dir

.
.fi
.
.SH "Customization"
.
.nf

Various settings can be changed in config.h file located in the program's directory.
.
.fi
